### ISSUE TITLE
Counld not find the artist "Taylor Swift"

### ISSUE THREAD

**Issue by mellinchou** [Ryan-Bauroth/Artistle#23]
Repro Steps:
1. go to "https://www.artistle.net/single-player"
2. enter "Taylor Swift" in the "Pick an Artist" input box 
3. click ENTER

Result:
a prompt shows up saying "We couldn't find the artist Taylor Swift"

Expected Result:
should be able to find Taylor Swift and begin game play
(please let me play Taylor Swift since the techyonic swiftle game isn't working :(((

**Comment by Ryan-Bauroth** [comment]
word I haven't checked this in ions. I believe the techyonic game is working at this time so that solves your issue, but to answer it: Some artists have their preview URL's (ie what this app uses) turned off for users that are not logged in. As this is still in development mode. I have to manually approve users to log in.
